config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  
  resources :users, only: [:new, :create]
  resources :sessions, only: [:create]
  resources :events
  resources :pictures
  resources :newsletter_emails, only: [:create, :index, :destroy]
  get "login", to: "sessions#new", as: "login"
  delete "logout", to: "sessions#destroy", as: "logout"
  resources :pages
  get ':id', to: 'pages#show', as: 'specific_page'
  root 'events#index'
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password, on: :create
end

app/controllers/users_controller.rb
class UsersController < WebsiteApplicationController
  def new
    @user = User.new
  end
  
  def create
    user = User.new(user_params)
    
    if user.save
      redirect_to root_url, notice: "Tak se nám zaregistrovala"
    else
      flash.now.alert("Hele, něco se dojebalo. Ještě to zkus ;]")
      render "new"
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h2>Zaregistruj se Pájo</h2>

<%= form_for(@user, url: users_url, method: :post) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br />
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br />
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br />
  <%= f.submit "Registruj pyčo" %>
<% end %>