config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  
  resources :users, only: [:new, :create]
  resources :sessions, only: [:create]
  resources :events
  resources :pictures
  resources :newsletter_emails, only: [:create, :index, :destroy]
  get "login", to: "sessions#new", as: "login"
  delete "logout", to: "sessions#destroy", as: "logout"
  resources :pages
  get ':id', to: 'pages#show', as: 'specific_page'
  root 'events#index'
  
  

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :title, :body, :event_type, :date_vernisage
  validates_presence_of :date_start, :date_end, if: :exhibition?
  
  enum event_type: [:exhibition, :concert, :workshop, :screening]
  
  def dates_line
    if exhibition?
      I18n.t('events.date_line.exhibition', 
              date_start: date_start.strftime('%d.%m.'), 
              date_end: date_end.strftime('%d.%m.'),
              date_vernisage: date_vernisage.strftime('%d.%m.%Y v %H:%M'))
    else
      date_vernisage.strftime('%d.%m.%Y v %H:%M')
    end
  end
end

app/controllers/events_controller.rb
class EventsController < WebsiteApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:show, :index]
  before_action :set_event_type_select_options, only: [:new, :edit, :create, :update]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_url, notice: t('events.controller.save_ok') }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_url, notice: t('events.controller.save_ok') }
#        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
#        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: t('events.controller.delete_ok') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end
    
    def set_event_type_select_options
      @event_type_select_options = Event.event_types.map do |key, value|
        [t('events.'+key), key]
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(
        :title, 
        :body, 
        :date_start, 
        :date_end, 
        :date_vernisage,
        :event_type
      )
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event, :html => { :class => "form-horizontal event" } do |f| %>
  <div class="button_box top">
    <%= f.submit t('forms.save'), :class => 'btn btn-primary' %>
    <%= link_to t('forms.cancel'),
              events_path, :class => 'btn btn-default' %>
  </div>

  <% if @event.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t('forms.errors.common') %>:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="col w350">
    <div class="control-group">
      <%= f.label :event_type, t('events.form.event_type') %>
      <%= f.select :event_type, options_for_select(@event_type_select_options, @event.event_type) %>
    </div>

    <div class="control-group">
      <%= f.label :title, t('events.form.title'), class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, class: 'form-control' %>
      </div>
    </div>

    <div class="control-group vernisage mt25">
      <%= f.label :date_vernisage, 
        t('events.form.date_vernisage'), 
        class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :date_vernisage, 
          class: 'form-control datetimepicker', 
          value: @event.date_vernisage.present? ? @event.date_vernisage.strftime('%-d. %-m. %Y %H:%M') : '' %>
        <p><%= t('events.form.date_description', date: Time.now.strftime('%-d. %-m. %Y %H:%M')) %></p>
      </div>
    </div>
  </div>

  <div class="col w350 mt40" id="date_start_end">
    <div class="control-group">
      <%= f.label :date_start, t('events.form.date_start'), class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :date_start, 
          class: 'form-control datepicker', 
          value: @event.date_start.present? ? @event.date_start.strftime('%-d. %-m. %Y') : '' %>
        <p><%= t('events.form.date_description', date: Time.now.strftime('%-d. %-m. %Y')) %></p>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :date_end, t('events.form.date_end'), class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :date_end, 
          class: 'form-control datepicker', 
          value: @event.date_end.present? ? @event.date_start.strftime('%-d. %-m. %Y') : '' %>
        <p><%= t('events.form.date_description', date: Time.now.strftime('%-d. %-m. %Y')) %></p>
      </div>
    </div>
  </div>

  <div class="cleaner"></div>

  <div class="control-group">
    <%= f.label :body, t('events.form.body'), :class => 'control-label' %>
    <div class="controls">
      <%= f.cktext_area :body, class: 'form-control', rows: 10, cols: 100 %>
    </div>
  </div>
  
  <div class="button_box bottom">
    <%= f.submit t('forms.save'), :class => 'btn btn-primary' %>
    <%= link_to t('forms.cancel'),
              events_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<h2><%= t('events.edit') %></h2>

<%= render :partial => 'form' %>

app/views/events/index.html.erb
<%- model_class = Event -%>
  <div class="action_box">
    <% if current_user.present? %>
      <%= link_to t('.new', :default => t("events.new")),
                  new_event_path,
                  :class => 'btn btn-primary' %>
    <% end %>
  </div>

<div id="events_list">
  <% @events.each do |event| %>
    <div class="event" id="event<%= event.id %>">
      <h2><%= link_to event.title, event_url(event) %></h2>
      <div class="action_box">
        <% if current_user.present? %>
        <%= link_to t('forms.edit'),
                      edit_event_path(event), :class => 'btn btn-default btn-xs' %>
        <%= link_to t('forms.destroy'),
                      event_path(event),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        <% end %>
      </div>
      <p class="basic_info">
        <span><%= t("events.#{event.event_type}") %>, <%= event.dates_line %></span></p>
        <div class="desc"><%= raw(event.body) %></div>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<%- model_class = Event -%>
<h2><%= t('events.new') %></h2>

<%= render :partial => 'form' %>

app/views/events/show.html.erb
<%- model_class = Event -%>
<h2><%= @event.title %></h2>
<% if current_user.present? %>
<div class="action_box">
<%= link_to t('events.list'),
              events_path, :class => 'btn btn-default'  %>
<%= link_to t('forms.edit'),
              edit_event_path(@event), :class => 'btn btn-default' %>
<%= link_to t('forms.destroy'),
              event_path(@event),
              :method => 'delete',
              :data => { :confirm => t('helpers.links.confirm') },
              :class => 'btn btn-danger' %>
</div>
<% end %>

<p class="basic_info">
  <%= t("events.#{@event.event_type}") %>,
  <%= @event.date_start.strftime('%d.%m.') %>
 - <%= @event.date_end.strftime('%d.%m.%Y') %>, vernisáž <%= @event.date_vernisage.strftime('%d.%m.%Y v %H:%M') %></p>

<%= raw(@event.body) %>