config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  
  resources :users, only: [:new, :create]
  resources :sessions, only: [:create]
  resources :events
  resources :pictures
  resources :newsletter_emails, only: [:create, :index, :destroy]
  get "login", to: "sessions#new", as: "login"
  delete "logout", to: "sessions#destroy", as: "logout"
  resources :pages
  get ':id', to: 'pages#show', as: 'specific_page'
  root 'events#index'
  
  

end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/websites/puda7/:id_:basename_:style.:extension",
                    :path => "/websites/puda7/:id_:basename_:style.:extension",
                    :styles => { :content => '550>', :thumb => '118x100#' },
                    :storage => :dropbox,
                    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
                    :dropbox_visibility => "public"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_attached_file :picture, 
    styles: { thumb: "150x", medium: "550x", large: "900x" }
  before_save :extract_dimensions
  
  validates_attachment :picture,
    presence: true, 
    content_type: { content_type: ['image/jpeg', 'image/png', 'image/gif'] },
    size: { in: 0..1.megabytes },
    file_name: { matches: [/\.png\Z/, /\.jpe?g\Z/, /\.gif\Z/]}
  
  def extract_dimensions
    tempfile = picture.queued_for_write[:original]
    unless tempfile.nil?
      geometry = Paperclip::Geometry.from_file(tempfile)
      self.dimensions = "#{geometry.width.to_i}x#{geometry.height.to_i}px"
    end
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to pictures_url, notice: t('pictures.controller.save_ok') }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to pictures_url, notice: t('pictures.controller.save_ok') }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: t('pictures.controller.delete_ok') }
      format.json { head :no_content }
    end
  end
  
#  def index_for_ckeditor
#    @pictures = Picture.all
#    render "index", layout: false
#  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:picture, :description)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for(@picture, multipart: true) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_page?(action: :new) %>
    <div class="field">
      <%= f.label :picture, t('pictures.picture') %><br>
      <%= f.file_field :picture %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :description, t('pictures.description') %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit t('forms.save') %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h2><%= t('pictures.edit').capitalize %></h2>

<div class="col w350">
<%= render 'form' %>

<%= link_to t('pictures.show'), @picture %> |
<%= link_to t('forms.cancel'), pictures_path %>
</div>
<div class="col w550">
  <%= image_tag @picture.picture.url(:medium) %>
</div>
<div class="cleaner"></div>

app/views/pictures/index.html.erb
<h2><%= t('pictures.pictures_list') %></h2>

<table>
  <thead>
    <tr>
      <th><%= t('pictures.picture') %></th>
      <th><%= t('pictures.dimensions') %></th>
      <th><%= t('pictures.description') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= image_tag picture.picture.url(:thumb), width: 150, alt: picture.picture, title: picture.picture %></td>
        <td><%= picture.dimensions %></td>
        <td><%= picture.description %></td>
        <td><%= link_to t('pictures.show'), picture %></td>
        <td><%= link_to t('forms.edit'), edit_picture_path(picture) %></td>
        <td><%= link_to t('forms.destroy'), picture, method: :delete, data: { confirm: t('helpers.links.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('pictures.new'), new_picture_path %>

app/views/pictures/new.html.erb
<h2><%= t('pictures.new').capitalize %></h2>

<%= render 'form' %>

<%= link_to t('helpers.links.back'), pictures_path %>

app/views/pictures/show.html.erb
<div class="col w550">
  <%= image_tag @picture.picture.url(:medium), alt: @picture.description %>
</div>
<div class="col w350">
<p>
  <strong><%= t('pictures.picture') %>:</strong>
  <%= @picture.picture %>
</p>

<p>
  <strong><%= t('pictures.dimensions') %>:</strong>
  <%= @picture.dimensions %>
</p>

<p>
  <strong><%= t('pictures.description') %>:</strong>
  <%= @picture.description %>
</p>
</div>
<div class="cleaner"></div>

<%= link_to t('forms.edit'), edit_picture_path(@picture) %> |
<%= link_to t('helpers.links.back'), pictures_path %>