config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  
  resources :users, only: [:new, :create]
  resources :sessions, only: [:create]
  resources :events
  resources :pictures
  resources :newsletter_emails, only: [:create, :index, :destroy]
  get "login", to: "sessions#new", as: "login"
  delete "logout", to: "sessions#destroy", as: "logout"
  resources :pages
  get ':id', to: 'pages#show', as: 'specific_page'
  root 'events#index'
  
  

end

app/models/newsletter_email.rb
class NewsletterEmail < ActiveRecord::Base
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/
  
  def to_s
    email
  end  
end

app/controllers/newsletter_emails_controller.rb
class NewsletterEmailsController < WebsiteApplicationController
  before_action :set_newsletter_email, only: :destroy
  before_action :authorize, except: :create
  
  def index
    @newsletter_emails = NewsletterEmail.all
  end
  
  def create
    @first_email = !NewsletterEmail.any?
    @newsletter_email = NewsletterEmail.new(email: params[:email])
    
    respond_to do |format|
      if @newsletter_email.save
        message = current_user.present? ? t('newsletter_emails.controller.create_ok_admin') 
          : t('newsletter.application_success')
        format.html { redirect_to :back, notice: message }
        format.js
        format.json { render json: @newsletter_email, status: :created, location: @newsletter_email }
      else
        format.html { redirect_to :back, notice: t('newsletter.application_error') }
        format.js
        format.json { render json: @newsletter_email.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @newsletter_email.destroy
    @no_emails = !NewsletterEmail.any?
    respond_to do |format|
      format.html { redirect_to newsletter_emails_url, notice: t('newsletter_emails.controller.delete_ok') }
      format.js
      format.json { head :no_content }
    end
  end
  
  private
  
  def set_newsletter_email
    @newsletter_email = NewsletterEmail.find(params[:id])
  end
end

app/helpers/newsletter_emails_helper.rb
module NewsletterEmailsHelper
end

app/views/newsletter_emails/_newsletter_email.html.erb
<tr class='destroy<%= newsletter_email.id %>'>
  <td><%= newsletter_email.email %></td>
  <td><%= newsletter_email.created_at.strftime("%d.%m.%Y %H:%M") %></td>
  <td align="center"><%= link_to "x", newsletter_email_path(newsletter_email), method: :delete, remote: true, class: "no_underline" %></td>
</tr>

app/views/newsletter_emails/_no_emails.html.erb
<tr>
  <td colspan="3">žádné e-maily tu nejsou uložené</td>
</tr>

app/views/newsletter_emails/create.js.erb
<% if @first_email %>
  $('div#content table tbody').html('');
<% else %>
  $('p#emails_list').append(', ');
<% end %>
$('p#emails_list').append('<%= @newsletter_email.email %>');
$('div#content table tbody').append('<%=j render @newsletter_email %>');
$('form input#email').val('');

app/views/newsletter_emails/destroy.js.erb
$('tr.destroy<%= @newsletter_email.id %>').remove();
<% if @no_emails %>
  $('div#content table tbody').append('<%= render partial: 'no_emails' %>');
<% end %>

app/views/newsletter_emails/index.html.erb
<h2>e-maily pro newsletter</h2>
<p id="emails_list">adresáti e-mailu:<br />
<%= @newsletter_emails.join(",") %></p>
<br />

<table width="100%">
  <thead>
  <tr>
    <th>e-mail</th>
    <th>přihlášený od</th>
    <th>smazat</th>
  </tr>
  </thead>
  <tbody>
    <%= render @newsletter_emails %>
    <% if  @newsletter_emails.empty? %>
      <%= render partial: 'no_emails' %>
    <% end %>
  </tbody>
</table>
<br />

<h3>přidat e-mail</h3>
<%= form_tag(newsletter_emails_url, method: :post, remote: true) do |f| %>
  <%= text_field_tag :email %>
  <%= submit_tag "přidat e-mail" %>
<% end %>